# bodn/ui/logo.py — Bodn pixel art logo for boot screen
#
# 16×16 multi-color logo: Norse mead vessel (Böðn)
# Each layer is a 1-bit 16×16 bitmap (32 bytes, row-major MSB-first).
# Layers are drawn back-to-front: vessel body, mead, rim, sparkles.

# Vessel body — rounded cauldron shape (amber/gold)
_BODY = bytes(
    [
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x0F,
        0xF0,  # ....########....
        0x18,
        0x18,  # ...##......##...
        0x30,
        0x0C,  # ..##........##..
        0x20,
        0x04,  # ..#..........#..
        0x20,
        0x04,  # ..#..........#..
        0x20,
        0x04,  # ..#..........#..
        0x30,
        0x0C,  # ..##........##..
        0x18,
        0x18,  # ...##......##...
        0x0F,
        0xF0,  # ....########....
        0x07,
        0xE0,  # .....######.....
        0x03,
        0xC0,  # ......####......
        0x00,
        0x00,  # ................
    ]
)

# Mead — liquid inside the vessel (crimson/red)
_MEAD = bytes(
    [
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x05,
        0xA0,  # .....#.##.#.....  (wave pattern)
        0x1F,
        0xF8,  # ...##########...
        0x1F,
        0xF8,  # ...##########...
        0x0F,
        0xF0,  # ....########....
        0x07,
        0xE0,  # .....######.....
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
    ]
)

# Rim — decorative top edge (bright white/gold)
_RIM = bytes(
    [
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x1F,
        0xF8,  # ...##########...
        0x10,
        0x08,  # ...#........#...
        0x1F,
        0xF8,  # ...##########...
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
    ]
)

# Sparkles — magic above the vessel (cyan)
_SPARKLES = bytes(
    [
        0x04,
        0x10,  # .....#.....#....
        0x00,
        0x40,  # .........#......
        0x02,
        0x08,  # ......#.....#...
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
        0x00,
        0x00,  # ................
    ]
)

# Layer list: (bitmap, color_key)
# Colors are resolved at draw time from the caller.
LAYERS = [
    (_BODY, "body"),
    (_MEAD, "mead"),
    (_RIM, "rim"),
    (_SPARKLES, "sparkle"),
]


def draw_logo(tft, x, y, colors, scale=4):
    """Draw the Bodn logo at (x, y) with the given scale.

    colors: dict mapping layer names to RGB565 color values.
        Expected keys: "body", "mead", "rim", "sparkle"
    """
    for bitmap, color_key in LAYERS:
        color = colors.get(color_key)
        if color is None:
            continue
        for row in range(16):
            hi = bitmap[row * 2]
            lo = bitmap[row * 2 + 1]
            word = (hi << 8) | lo
            if word == 0:
                continue
            for col in range(16):
                if word & (0x8000 >> col):
                    if scale == 1:
                        tft.pixel(x + col, y + row, color)
                    else:
                        tft.fill_rect(
                            x + col * scale, y + row * scale, scale, scale, color
                        )
