[wokwi]
version = 1
firmware = "ESP32_GENERIC_S3-20251209-v1.27.0.bin"
elf = "ESP32_GENERIC_S3-20251209-v1.27.0.bin"
rfc2217ServerPort = 5555
gdbServerPort = 3333

[[chip]]
name = "mcp23017"
binary = "mcp23017.chip.wasm"

[[chip]]
name = "pca9685"
binary = "pca9685.chip.wasm"

[net]
gateway = "ws://localhost:9011"

# Port forwarding (requires Wokwi Private Gateway).
# Download: https://github.com/wokwi/wokwigw/releases
# Run: wokwigw   (then F1 → "Enable Private Wokwi IoT Gateway" in VS Code)
[[net.forward]]
from = "localhost:9080"
to = "target:80"
