[wokwi]
version = 1
firmware = "ESP32_GENERIC_S3-20251209-v1.27.0.bin"
elf = "ESP32_GENERIC_S3-20251209-v1.27.0.bin"
rfc2217ServerPort = 5555

[net]
gateway = "ws://localhost:9011"

# Port forwarding (requires Wokwi Private Gateway).
# Download: https://github.com/wokwi/wokwigw/releases
# Run: wokwigw   (then F1 → "Enable Private Wokwi IoT Gateway" in VS Code)
[[net.forward]]
from = "localhost:9080"
to = "target:80"
