include(${CMAKE_CURRENT_LIST_DIR}/audiomix/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/spidma/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/draw/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/mcpinput/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/neopixel/micropython.cmake)
