# bodn/sounds.py — audio asset catalog
#
# Two catalogs live here:
#
#   SOUNDS — procedural tone sequences for UI feedback.
#             Each entry is [(freq_hz, duration_ms, wave), ...].
#             Use AudioEngine.play_sound(name) to trigger.
#
#   WAV    — filesystem paths for pre-recorded WAV files (SFX and music).
#             Use AudioEngine.play(WAV["sfx"]["click"]) etc.
#             Soundboard paths are NOT here — they are dynamic and owned by
#             soundboard_rules.py (discovered at runtime from /sounds/bank_N/).
#
# Converted device-ready WAVs live in firmware/sounds/ and are generated by
# tools/convert_audio.py from the high-quality sources in assets/audio/source/.
# The source-of-truth for soundboard content and metadata is
# assets/audio/soundboard.json.

# WAV file paths on the device filesystem.
# Add an entry here when you add a new converted file to firmware/sounds/sfx/
# or firmware/sounds/music/.  Keep keys stable — they are referenced in code.
#
# TTS paths are NOT listed here — use bodn.tts.say(key, audio) instead.
# say() resolves the language-partitioned path automatically via bodn.assets.resolve.
WAV = {
    "sfx": {
        "nav_click": "/sounds/sfx/pop.wav",
        "error": "/sounds/sfx/error.wav",
        "reward": "/sounds/sfx/reward.wav",
    },
    "music": {
        # e.g. "ambient": "/sounds/music/ambient.wav",
    },
    # "tts" category lives at /sounds/tts/{lang}/{key}.wav — use bodn.tts.say().
}

SOUNDS = {
    # Select — rising chirp when entering a mode
    "select": [(660, 60, "sine"), (880, 80, "sine")],
    # Back — descending tone when leaving a screen
    "back": [(660, 60, "sine"), (440, 80, "sine")],
    # Correct answer — bright ascending
    "correct": [(660, 80, "sine"), (880, 120, "sine")],
    # Wrong answer — low flat buzz
    "wrong": [(220, 250, "square")],
    # Generic UI feedback (button press, toggle)
    "boop": [(440, 100, "sine")],
    # Startup — "To-to-ro, To-to-ro" from My Neighbor Totoro chorus
    # Melody: G4-G4-E4 (×2), rhythm at ~120 BPM: eighth-eighth-dotted quarter
    "start": [
        (392, 200, "sine"),  # To-    (G4, eighth)
        (392, 200, "sine"),  # -to-   (G4, eighth)
        (330, 450, "sine"),  # -ro    (E4, dotted quarter — held)
        (0, 100, "sine"),  #        (breath)
        (392, 200, "sine"),  # To-    (G4, eighth)
        (392, 200, "sine"),  # -to-   (G4, eighth)
        (330, 600, "sine"),  # -ro    (E4, half — final hold)
    ],
    # Level up / puzzle complete — triumphant
    "complete": [(660, 100, "sine"), (880, 100, "sine"), (1100, 150, "sine")],
    # Timer warning — urgent double beep
    "warning": [(880, 80, "sine"), (0, 60, "sine"), (880, 80, "sine")],
    # Rule switch (Rule Follow game)
    "rule_switch": [(587, 200, "sine")],
}
