#!/usr/bin/env python3
"""Build firmware/bodn/web_ui.py from tools/web/ source files.

Pipeline:
  1. Read tools/web/{index.html,style.css,app.js,login.html}.
  2. Conservative minify: strip comments, collapse whitespace, drop blank lines.
  3. Inline CSS and JS into index.html.
  4. Gzip with level 9 (browsers always accept gzip).
  5. Emit firmware/bodn/web_ui.py with HTML, HTML_GZ, LOGIN_HTML, LOGIN_GZ.

The generated module ships gzip-precomputed bytes; the device never has to
compress at runtime (stock MicroPython's deflate doesn't support write).
"""

from __future__ import annotations

import gzip
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "tools" / "web"
OUT = ROOT / "firmware" / "bodn" / "web_ui.py"


_CSS_COMMENT = re.compile(r"/\*.*?\*/", re.S)
_HTML_COMMENT = re.compile(r"<!--.*?-->", re.S)


def minify_css(s: str) -> str:
    s = _CSS_COMMENT.sub("", s)
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"\s*([{}:;,>])\s*", r"\1", s)
    s = re.sub(r";}", "}", s)
    return s.strip()


def minify_js(s: str) -> str:
    out = []
    for line in s.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("//"):
            continue
        out.append(stripped)
    return "\n".join(out)


def minify_html(s: str) -> str:
    s = _HTML_COMMENT.sub("", s)
    return "\n".join(line.strip() for line in s.splitlines() if line.strip())


def render_main() -> str:
    style = minify_css((WEB / "style.css").read_text(encoding="utf-8"))
    script = minify_js((WEB / "app.js").read_text(encoding="utf-8"))
    html = (WEB / "index.html").read_text(encoding="utf-8")
    html = html.replace("{{STYLE}}", style).replace("{{SCRIPT}}", script)
    return minify_html(html)


def render_login() -> str:
    return minify_html((WEB / "login.html").read_text(encoding="utf-8"))


def _py_str(s: str) -> str:
    """Encode as a Python triple-quoted string literal."""
    return '"""' + s.replace("\\", "\\\\").replace('"""', r"\"\"\"") + '"""'


def build() -> None:
    html = render_main()
    login = render_login()

    html_bytes = html.encode("utf-8")
    login_bytes = login.encode("utf-8")
    html_gz = gzip.compress(html_bytes, compresslevel=9, mtime=0)
    login_gz = gzip.compress(login_bytes, compresslevel=9, mtime=0)

    body = []
    body.append("# Generated by tools/build-web-ui.py -- do not edit by hand.\n")
    body.append("# Source: tools/web/{index.html,style.css,app.js,login.html}\n")
    body.append("#\n")
    body.append("# HTML / LOGIN_HTML are kept as a fallback for clients that don't\n")
    body.append("# accept gzip; HTML_GZ / LOGIN_GZ are what real browsers receive.\n\n")
    body.append("HTML = " + _py_str(html) + "\n\n")
    body.append("LOGIN_HTML = " + _py_str(login) + "\n\n")
    body.append("HTML_GZ = " + repr(html_gz) + "\n")
    body.append("LOGIN_GZ = " + repr(login_gz) + "\n")

    OUT.write_text("".join(body), encoding="utf-8")

    print(
        f"  HTML : {len(html_bytes):>6} B raw -> {len(html_gz):>5} B gz "
        f"({100 * len(html_gz) / max(1, len(html_bytes)):.1f}%)"
    )
    print(
        f"  LOGIN: {len(login_bytes):>6} B raw -> {len(login_gz):>5} B gz "
        f"({100 * len(login_gz) / max(1, len(login_bytes)):.1f}%)"
    )
    print(f"  Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    try:
        build()
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
