#!/usr/bin/env python3
"""
Audio asset conversion pipeline for Bodn ESP32.

Source (high-quality) files live in assets/audio/source/:
  soundboard/bank_N/   — numbered slot files for each bank (0.wav – 7.wav)
  soundboard/arcade/   — shared arcade button sounds (0.wav – 4.wav)
  sfx/                 — UI and game sound effects
  music/               — background music
  tts/{sv,en}/         — Piper TTS flash files (generated by tools/generate_tts.py)

Output routing (all 16 kHz mono PCM):
  Flash (firmware/sounds/) — SFX, flash TTS, soundboard manifest
  SD    (build/sounds/)    — soundbanks, arcade, music
  SD    (build/tts_converted/) — SD TTS keys

Use tools/sd-sync.py to copy build/ outputs to the SD card.
The soundboard manifest (firmware/sounds/manifest.json) is generated from
assets/audio/soundboard.json — never edit the device manifest by hand.

Usage:
  uv run python tools/convert_audio.py                  # convert everything
  uv run python tools/convert_audio.py --dry-run        # show what would be done
  uv run python tools/convert_audio.py --force          # reconvert even if up-to-date
  uv run python tools/convert_audio.py --no-normalize   # skip loudness normalization
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
ASSETS_DIR = REPO_ROOT / "assets" / "audio"
SOURCE_DIR = ASSETS_DIR / "source"
SOUNDBOARD_JSON = ASSETS_DIR / "soundboard.json"
FIRMWARE_SOUNDS = REPO_ROOT / "firmware" / "sounds"
DEVICE_MANIFEST = FIRMWARE_SOUNDS / "manifest.json"
BUILD_DIR = REPO_ROOT / "build"
BUILD_SOUNDS = BUILD_DIR / "sounds"

# Target device format
FFMPEG_CONVERT = [
    "-ar",
    "16000",
    "-ac",
    "1",
    "-sample_fmt",
    "s16",
    "-acodec",
    "pcm_s16le",
]

# EBU R128 loudness normalization: -16 LUFS integrated, -1.5 dBTP true peak
LOUDNORM_FILTER = ["loudnorm=I=-16:TP=-1.5:LRA=11"]

_converted = 0
_skipped = 0
_missing = 0
_errors = 0


def check_ffmpeg():
    if not shutil.which("ffmpeg"):
        sys.exit("ERROR: ffmpeg not found. Install it: brew install ffmpeg")


def _convert_file(
    src: Path, dst: Path, dry_run: bool, force: bool, normalize: bool
) -> str:
    """
    Convert src → dst.  Returns 'converted', 'skipped', 'missing', or 'error'.
    """
    global _converted, _skipped, _missing, _errors

    if not src.exists():
        print(f"  missing   {src.relative_to(REPO_ROOT)}")
        _missing += 1
        return "missing"

    if not force and dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
        _skipped += 1
        return "skipped"

    rel_src = src.relative_to(REPO_ROOT)
    rel_dst = dst.relative_to(REPO_ROOT)
    if dry_run:
        print(f"  would convert  {rel_src}  →  {rel_dst}")
        _converted += 1
        return "converted"

    dst.parent.mkdir(parents=True, exist_ok=True)
    af_args = ["-af", *LOUDNORM_FILTER] if normalize else []
    cmd = (
        ["ffmpeg", "-y", "-loglevel", "error", "-i", str(src)]
        + af_args
        + FFMPEG_CONVERT
        + [str(dst)]
    )
    result = subprocess.run(cmd, capture_output=True)
    if result.returncode != 0:
        err = result.stderr.decode(errors="replace").strip()[-300:]
        print(f"  ERROR  {src.name}: {err}", file=sys.stderr)
        _errors += 1
        return "error"

    kib = dst.stat().st_size // 1024
    print(f"  converted  {rel_src}  →  {rel_dst}  ({kib} KiB)")
    _converted += 1
    return "converted"


def process_soundboard(dry_run: bool, force: bool, normalize: bool):
    """Convert soundboard source files and regenerate firmware/sounds/manifest.json."""
    if not SOUNDBOARD_JSON.exists():
        print("assets/audio/soundboard.json not found — skipping soundboard.")
        return

    with open(SOUNDBOARD_JSON) as f:
        raw = f.read()
    # Strip trailing commas before closing braces/brackets — JSON doesn't allow
    # them, but they're easy to leave when pasting stubs.
    raw = re.sub(r",(\s*[}\]])", r"\1", raw)
    try:
        sb = json.loads(raw)
    except json.JSONDecodeError as e:
        sys.exit(f"ERROR: soundboard.json is not valid JSON: {e}")

    manifest_banks = {}

    # --- Banks ---
    for bank_key, bank_val in sb.get("banks", {}).items():
        try:
            bank_idx = int(bank_key)
        except (ValueError, TypeError):
            continue

        # Build the device manifest entry: keep display fields, drop 'source'.
        manifest_bank = {}
        for field in ("name", "name_sv", "name_en", "color"):
            if bank_val.get(field):
                manifest_bank[field] = bank_val[field]

        manifest_slots = {}
        for slot_key, slot_val in bank_val.get("slots", {}).items():
            try:
                slot_idx = int(slot_key)
            except (ValueError, TypeError):
                continue

            # Convert source WAV if specified
            src_rel = slot_val.get("source") if isinstance(slot_val, dict) else None
            if src_rel:
                src = SOURCE_DIR / src_rel
                dst = BUILD_SOUNDS / f"bank_{bank_idx}" / f"{slot_idx}.wav"
                _convert_file(src, dst, dry_run, force, normalize)

            # Collect non-empty display labels for the manifest
            if isinstance(slot_val, dict):
                label = {k: v for k, v in slot_val.items() if k != "source" and v}
                if label:
                    manifest_slots[slot_key] = label
            elif isinstance(slot_val, str) and slot_val:
                manifest_slots[slot_key] = slot_val

        if manifest_slots:
            manifest_bank["slots"] = manifest_slots
        manifest_banks[bank_key] = manifest_bank

    # --- Arcade ---
    # Slot keys are button colors mapped to hardware indices (config.py PWM_CH_ARC*).
    arcade_color_to_idx = {"yellow": 0, "red": 1, "blue": 2, "green": 3, "white": 4}
    manifest_arcade = {}
    for slot_key, slot_val in sb.get("arcade", {}).get("slots", {}).items():
        slot_idx = arcade_color_to_idx.get(slot_key)
        if slot_idx is None:
            try:
                slot_idx = int(slot_key)
            except (ValueError, TypeError):
                continue

        src_rel = slot_val.get("source") if isinstance(slot_val, dict) else None
        if src_rel:
            src = SOURCE_DIR / src_rel
            dst = BUILD_SOUNDS / "arcade" / f"{slot_idx}.wav"
            _convert_file(src, dst, dry_run, force, normalize)

        # Collect display labels for the manifest
        if isinstance(slot_val, dict):
            label = {k: v for k, v in slot_val.items() if k not in ("source",) and v}
            if label:
                manifest_arcade[str(slot_idx)] = label

    # --- Write device manifest ---
    manifest = {"banks": manifest_banks}
    if manifest_arcade:
        manifest["arcade"] = manifest_arcade
    if dry_run:
        print(f"  would write  firmware/sounds/manifest.json")
    else:
        DEVICE_MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        with open(DEVICE_MANIFEST, "w") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)
            f.write("\n")
        print(f"  wrote  firmware/sounds/manifest.json")


def process_directory(
    category: str,
    dry_run: bool,
    force: bool,
    normalize: bool,
    target: str = "flash",
):
    """Convert all WAVs in assets/audio/source/<category>/.

    target: "flash" → firmware/sounds/<category>/
            "sd"    → build/sounds/<category>/
    """
    src_dir = SOURCE_DIR / category
    if not src_dir.exists():
        print(f"  assets/audio/source/{category}/ not found — skipping.")
        return

    wavs = sorted(src_dir.rglob("*.wav"))
    if not wavs:
        print(f"  no WAV files in assets/audio/source/{category}/")
        return

    dst_dir = (BUILD_SOUNDS if target == "sd" else FIRMWARE_SOUNDS) / category
    for src in wavs:
        rel = src.relative_to(src_dir)
        dst = dst_dir / rel
        _convert_file(src, dst, dry_run, force, normalize)


def process_tts_sd(dry_run: bool, force: bool, normalize: bool):
    """Convert SD TTS staging files from build/tts/ → build/tts_converted/."""
    src_dir = BUILD_DIR / "tts"
    if not src_dir.exists():
        print(f"  build/tts/ not found — run tools/generate_tts.py first.")
        return

    wavs = sorted(src_dir.rglob("*.wav"))
    if not wavs:
        print(f"  no WAV files in build/tts/")
        return

    dst_dir = BUILD_DIR / "tts_converted"
    for src in wavs:
        rel = src.relative_to(src_dir)
        dst = dst_dir / rel
        _convert_file(src, dst, dry_run, force, normalize)


def process_story_tts(dry_run: bool, force: bool, normalize: bool):
    """Convert story TTS and stage story scripts into self-contained packages.

    Converts: build/story_tts_raw/{id}/{lang}/*.wav → build/stories/{id}/tts/{lang}/*.wav
    Copies:   assets/stories/{id}/script.py          → build/stories/{id}/script.py
              firmware/bodn/stories/__init__.py       → build/stories/forest_walk/script.py
    """
    raw_dir = BUILD_DIR / "story_tts_raw"
    stories_dir = BUILD_DIR / "stories"

    # Convert TTS audio
    if raw_dir.exists():
        wavs = sorted(raw_dir.rglob("*.wav"))
        if wavs:
            for src in wavs:
                # src: build/story_tts_raw/{story_id}/{lang}/{node}.wav
                # dst: build/stories/{story_id}/tts/{lang}/{node}.wav
                rel = src.relative_to(raw_dir)
                parts = rel.parts  # (story_id, lang, filename)
                if len(parts) == 3:
                    dst = stories_dir / parts[0] / "tts" / parts[1] / parts[2]
                    _convert_file(src, dst, dry_run, force, normalize)
        else:
            print(f"  no WAV files in build/story_tts_raw/")
    else:
        print(
            f"  build/story_tts_raw/ not found — run tools/generate_story_tts.py first."
        )

    # Stage story scripts into build/stories/
    _stage_story_scripts(dry_run, force)


def _stage_story_scripts(dry_run: bool, force: bool):
    """Copy story script.py files into build/stories/ for SD sync."""
    stories_dir = BUILD_DIR / "stories"
    assets_stories = REPO_ROOT / "assets" / "stories"

    if not assets_stories.exists():
        return

    for entry in sorted(assets_stories.iterdir()):
        src = entry / "script.py"
        if not src.is_file():
            continue
        dst = stories_dir / entry.name / "script.py"
        if not force and dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
            continue
        if dry_run:
            print(
                f"  would copy  {src.relative_to(REPO_ROOT)}  →  {dst.relative_to(REPO_ROOT)}"
            )
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            print(
                f"  copied  {src.relative_to(REPO_ROOT)}  →  {dst.relative_to(REPO_ROOT)}"
            )


def print_summary(dry_run: bool):
    label = "Would convert" if dry_run else "Converted"
    print(
        f"\n{label}: {_converted}  |  Up-to-date: {_skipped}  |  Missing source: {_missing}  |  Errors: {_errors}"
    )
    if _errors:
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Convert audio assets for Bodn ESP32")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be converted without doing it",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Reconvert even if output is already up-to-date",
    )
    parser.add_argument(
        "--no-normalize",
        action="store_true",
        help="Skip EBU R128 loudness normalization (loudnorm)",
    )
    args = parser.parse_args()
    normalize = not args.no_normalize

    check_ffmpeg()

    print("=== Soundboard (→ SD) ===")
    process_soundboard(args.dry_run, args.force, normalize)

    print("\n=== SFX (→ flash) ===")
    process_directory("sfx", args.dry_run, args.force, normalize)

    print("\n=== Music (→ SD) ===")
    process_directory("music", args.dry_run, args.force, normalize, target="sd")

    print("\n=== TTS (flash) ===")
    process_directory("tts", args.dry_run, args.force, normalize)

    print("\n=== TTS (SD staging) ===")
    process_tts_sd(args.dry_run, args.force, normalize)

    print("\n=== Story packages (TTS + scripts → SD) ===")
    process_story_tts(args.dry_run, args.force, normalize)

    print_summary(args.dry_run)


if __name__ == "__main__":
    main()
